apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-cluster
  labels:
    name: devops-cluster
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: devops-tp
  template:
    metadata:
      labels:
        name: devops-tp
    spec:
      containers:
        - name: devops-tp-mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "isen_user_password"
            - name: MYSQL_USER
              value: "isen_user"
          ports:
            - containerPort: 3306
              name: mysql
              hostPort: 4567
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
        - name: devops-tp-api
          image: mizkyosia/devops-tp-final
          resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
          restartPolicy: Always
          imagePullPolicy: Always
