apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: devops-mysql
  labels:
    app: devops-mysql
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: devops-mysql
  template:
    metadata:
      labels:
        app: devops-mysql
    spec:
      containers:
        - name: devops-tp-mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "isen_user_password"
            - name: MYSQL_USER
              value: "isen_user"
            - name: MYSQL_PASSWORD
              value: "isen_user_password"
            - name: MYSQL_DATABASE
              value: "devops_db"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api
  labels:
    app: devops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  template:
    metadata:
      labels:
        app: devops-api
    spec:
      containers:
        - name: devops-tp-api
          image: mizkyosia/devops-tp-final
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: "isen_user"
            - name: DB_USERNAME_PASSWORD
              value: "isen_user_password"
            - name: DB_NAME
              value: "devops_db"
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: devops-mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30000
      protocol: TCP
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: devops-api
  ports:
    - name: http
      port: 80
      targetPort: 30001
      nodePort: 9100
      protocol: TCP
  type: NodePort
