[webservers]
vm-kubernetes ansible_host=192.168.56.10 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'
vm-monitoring ansible_host=192.168.56.11 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'