---
- hosts: all
  become: true
  tasks:
    - name: Afficher OS
      debug:
        msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Installer dépendances
      apt:
        pkg:
          - wget
          - curl
          - git
        state: latest
        update_cache: yes
    
    - name: Installation script k3s
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        executable: /bin/bash
    
    - name: Copier manifest.yaml
      copy:
        src: manifest.yaml
        dest: /home/vagrant/manifest.yaml