---
- hosts: vm-kubernetes
  become: true
  tasks:
    - name: Debug hostvars
      debug:
        var: hostvars['vm-kubernetes'].ansible_host

    - name: Installer dépendances
      apt:
        pkg:
          - wget
          - curl
          - git
        state: latest
        update_cache: yes
    
    - name: Installation script k3s
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        executable: /bin/bash
    
    - name: Copier manifest.yaml
      copy:
        src: ../manifest.yml
        dest: /home/vagrant/manifest.yaml